package com.pacman.screens;

public enum WallAtlasRegion {
    EMPTY(0), // 0
    INNER_WALL_HORIZONTAL_BOTTOM_SIDE(1), // 1
    INNER_WALL_HORIZONTAL_TOP_SIDE(2), // 2
    INNER_WALL_VERTICAL_LEFT_SIDE(3), // 3
    INNER_WALL_VERTICAL_RIGHT_SIDE(4), // 4
    INTERSECTION_BOTTOM_END_LEFT(5), // 5
    INTERSECTION_BOTTOM_END_RIGHT(6), // 6
    INTERSECTION_LEFT_END_BOTTOM(7), // 7
    INTERSECTION_LEFT_END_TOP(8), // 8
    INTERSECTION_RIGHT_END_BOTTOM(9), // 9
    INTERSECTION_RIGHT_END_TOP(10), // 10
    INTERSECTION_TOP_END_LEFT(11), // 11
    INTERSECTION_TOP_END_RIGHT(12), // 12
    JAIL_BOTTOM_LEFT_CORNER(13), // 13
    JAIL_BOTTOM_RIGHT_CORNER(14), // 14
    JAIL_DOOR(15), // 15
    JAIL_TOP_LEFT_CORNER(16), // 16
    JAIL_TOP_RIGHT_CORNER(17), // 17
    OUTER_WALL_BOTTOM_LEFT_CORNER(18), // 18
    OUTER_WALL_BOTTOM_RIGHT_CORNER(19), // 19
    OUTER_WALL_HORIZONTAL_BOTTOM(20), // 20
    OUTER_WALL_HORIZONTAL_TOP(21), // 21
    OUTER_WALL_TOP_LEFT_CORNER(22), // 22
    OUTER_WALL_TOP_RIGHT_CORNER(23), // 23
    OUTER_WALL_VERTICAL_LEFT(24), // 24
    OUTER_WALL_VERTICAL_RIGHT(25), // 25
    PELLET_LARGE(26), // 26
    PELLET_SMALL(27), // 27
    T_SHAPE_HORIZONTAL_BASE_DOWN_INTERSECTION_LEFT_SIDE(28), // 28
    T_SHAPE_HORIZONTAL_BASE_DOWN_INTERSECTION_RIGHT_SIDE(29), // 29
    T_SHAPE_HORIZONTAL_BASE_UP_INTERSECTION_LEFT_SIDE(30), // 30
    T_SHAPE_HORIZONTAL_BASE_UP_INTERSECTION_RIGHT_SIDE(31), // 31
    T_SHAPE_VERTICAL_BASE_LEFT_INTERSECTION_BOTTOM_SIDE(32), // 32
    T_SHAPE_VERTICAL_BASE_LEFT_INTERSECTION_TOP_SIDE(33), // 33
    T_SHAPE_VERTICAL_BASE_RIGHT_INTERSECTION_BOTTOM_SIDE(34), // 34
    T_SHAPE_VERTICAL_BASE_RIGHT_INTERSECTION_TOP_SIDE(35), // 35
    WALL_SQUARE_BOTTOM_LEFT_CORNER(36), // 36
    WALL_SQUARE_BOTTOM_RIGHT_CORNER(37), // 37
    WALL_SQUARE_TOP_LEFT_CORNER(38), // 38
    WALL_SQUARE_TOP_RIGHT_CORNER(39); // 39


    private final int value;

    WallAtlasRegion(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static WallAtlasRegion fromValue(int value) {
        for (WallAtlasRegion type : values()) {
            if (type.value == value) {
                return type;
            }
        }
        return EMPTY; // default if unknown
    }

}
